- hosts: localhost
  become: true
  tasks:
  - name: Install SSH
    apt: name=openssh-server

  - name: Install zenmap
    apt: name=zenmap
   
  - name: Install Visual Studio Code
    command: snap install vscode --classic
    
  - name: Install Adobe Flash Player
    apt: name=flashplugin-installer

  - name: Install ICA Client for Citrix
  apt: deb="/home/pmoody/Downloads/icaclient_18.10.0.11_amd64.deb"
