- hosts: localhost
  become: true
  tasks:
  - name: Install SSH
    apt: name=openssh-server

  - name: Install zenmap
    apt: name=zenmap
   
  - name: Install Visual Studio Code
    command: snap install vscode --classic
    
  - name: Install Adobe Flash Player
    apt: name=flashplugin-installer

  - name: Install ICA Client for Citrix
    apt: deb="/home/pmoody/Downloads/icaclient_18.10.0.11_amd64.deb"
    become: sudo

  - name: Install kismet
    apt: name=kismet

  - name: Install vlc
    apt: name=vlc

  - name: Install python-pip
    apt: name=python-pip

  - name: Install AWS CLI
    apt: name=awscli

  - name: Install gparted
    apt: name=gparted
    
  - name: Install Docker
    apt: name=docker.io 

  - name: Create Playbooks directory
    file:
      path: home/pmoody/Documents/Playbooks
      state: directory
      owner: pmoody
      mode: 0775

  - name: Create SQL directory
    file:
      path: ~/Documents/SQL
      state: directory
      owner: pmoody
      mode: 0775
      
  - git:
      repo: https://github.com/pmoody1330/Playbooks.git
      dest: ~/Documents/Playbooks
      force: yes
