- hosts: localhost
  become: true
  tasks:
  - name: Install SSH
    apt: name=openssh-server

  - name: Install zenmap
    apt: name=zenmap
   
  - name: Install Visual Studio Code
    command: snap install vscode --classic
