- hosts: localhost
  become: true
  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
    
  - name: Install SSH
    apt: name=openssh-server

  - name: Install zenmap
    apt: name=zenmap
   
  - name: Install Visual Studio Code
    command: snap install vscode --classic

  - name: Install Notepad++
    command: snap install notepad-plus-plus
    
  - name: Install Adobe Flash Player
    apt: name=flashplugin-installer

  - name: Install ICA Client for Citrix
    apt: deb="/home/pmoody/Downloads/icaclient_19.3.0.5_amd64.deb"
    become: sudo

  - name: Install kismet
    apt: name=kismet

  - name: Install vlc
    apt: name=vlc

  - name: Install python-pip
    apt: name=python-pip
    
  - name: Install python3-pip
    apt: name=python3-pip

  - name: Install AWS CLI
    apt: name=awscli

  - name: Install gparted
    apt: name=gparted
    
  - name: Install Docker
    apt: name=docker.io 

  - name: Create Playbooks directory
    file:
      path: home/pmoody/Documents/Playbooks
      state: directory
      owner: pmoody
      mode: 0775

  - name: Create SQL directory
    file:
      path: ~/Documents/SQL
      state: directory
      owner: pmoody
      mode: 0775
      
  - git:
      repo: 'https://github.com/pmoody1330/Playbooks.git'
      dest: Playbooks
      force: yes
      refspec: '+refs/pull/*:refs/heads/*'

  - git:
      repo: 'https://pmoody_TN@bitbucket.org/pmoody_TN/powershell_private.git'
      dest: Powershell
      force: yes
      refspec: '+refs/pull/*:refs/heads/*'
      
  - git:
      repo: 'https://github.com/ScottEvtuch/PSLastPass.git'
      dest: PSLastPass
      force: yes
      refspec: '+refs/pull/*:refs/heads/*'
