- hosts: localhost
  become: true
  tasks:
  - name: Install htop
    apt: name=htop

  - name: Install mc
    apt: name=mc
   
  - name: Install tmux
    apt: name=tmux

  - name: Install fish
    apt: name=fish

  - name: Install vlan
    apt: name=vlan
